### ISSUE TITLE
problem on running LM fine-tuning with fp16 on colab

### ISSUE THREAD

**Issue by marcusau** [ThilinaRajapakse/simpletransformers#685]
**Describe the bug**
We can run the fine-tuning with fp16 on colab as the script shows the following error when we set fp19=true in args:

**Screenshots**
![image](https://user-images.githubusercontent.com/31444195/91814595-f3d71580-ec66-11ea-9032-b0a822ad5c8c.png)

**Desktop (please complete the following information):**
 - OS

**Additional context**

**Comment by ThilinaRajapakse** [comment]
This is fixed now, right?

**Comment by marcusau** [comment]
working on it.. give me 10 mins

**Comment by marcusau** [comment]
it works now . thanks a lot

**Comment by marcusau** [comment]
sorry

problem remains

![image](https://user-images.githubusercontent.com/31444195/92327038-59713a80-f089-11ea-977a-f42675bf4860.png)

**Comment by marcusau** [comment]
this is the whole warning 
![image](https://user-images.githubusercontent.com/31444195/92327066-8d4c6000-f089-11ea-9818-3602172cca26.png)

**Comment by marcusau** [comment]
because the training period will be extra-ordinary long without apex fp16...

hope you understand the importance of this issue.  Thanks

**Comment by MirjamOdile** [comment]
Hi

I am having the same problem. I first encountered the problem on a project of my own, but it persists on the minimal example with wikitext-2 tokens. 

This is running on a local conda environment set up as recommended with pytorch 1.6.0, cudatoolkit 10.2, transformers 3.1.0, on an NVIDIA RTX 2080 Ti. The problem does not persist running on CPU, but completing the original task on CPU is infeasable.
I have tried with a fresh pull from the main branch, but with no luck.

Any help is appreciated. Thank you.
